Added PCA prototype on arduino using Lanczos Algorithm
1chipML/1chipML pull request #28
Opened 2023-03-12 23:56 UTC by felix642

Added a prototype to reduce the dimension of a classification dataset. 
This algorithm uses the Lanczos algorithm first and the Jacobi algorithm after.

2023-03-12 23:56 UTC, felix642 commented
Also, we need to merge the Jacobi PR before merging this PR

2023-03-18 15:52 UTC, bisson2000 approved these changes
gfm

2023-03-21 16:17 UTC, GM07 reviewed
I left a small comment, but otherwise looks good to me

2023-03-21 16:17 UTC, GM07 commented on prototype/pca_lanczos/pca.py
> +    plt.ylabel('Première composante principale')
Maybe put the titles in english since the library is in english

2023-03-23 13:52 UTC, nicholaslegrand102 commented on prototype/pca_lanczos/README.md
The README is empty

2023-03-23 13:53 UTC, nicholaslegrand102 requested changes
Looks good but it is missing the documentation

2023-03-23 16:44 UTC, nicholaslegrand102 approved these changes
Looks good to me

2023-03-25 19:06 UTC, florenceCloutier requested changes
Left a few comments :)

2023-03-25 19:06 UTC, florenceCloutier commented on prototype/pca_lanczos/README.md
> +This prototype showcase the application of a principal component analysis (PCA) on a classification dataset.
showcases (with an s)

2023-03-25 19:06 UTC, florenceCloutier commented on prototype/pca_lanczos/pca/pca.ino
> +void readElement(void* element, const size_t sizeOfElement) {
Include the utils folder to use these functions without code duplication

2023-03-25 19:10 UTC, nicholaslegrand102 commented on prototype/pca_lanczos/pca/pca.ino
> +void computeCovarianceMatrix(uint8_t* ptr, uint8_t nbElemsCov, uint8_t nbElems, double* output)
Please add comments for all of these functions

2023-03-26 20:21 UTC, nicholaslegrand102 requested changes
Looks good except for the comments

2023-03-27 13:31 UTC, florenceCloutier approved these changes
Good for me :)

2023-03-27 16:38 UTC, nicholaslegrand102 approved these changes
Looks good to me

2023-03-27 19:13 UTC, merged