Curve fitting prototype using gradient descent
1chipML/1chipML pull request #34
Opened 2023-03-25 17:03 UTC by zedfly

Curve fitting prototype on the arduino using the Gradient-Descent method

2023-03-25 18:04 UTC, nicholaslegrand102 commented on prototype/gradient_descent/gradient_descent.ino
> +gradient_real cost(gradient_real p[]) {
Please add comments describing the functions

2023-03-25 18:06 UTC, nicholaslegrand102 commented on prototype/gradient_descent/anomaly_detection.py
> +    #detectAnomaly("data/Cubic_20%_outliers.csv", 3, 3000)
missing newline

2023-03-25 18:07 UTC, nicholaslegrand102 commented on prototype/gradient_descent/anomaly_detection.py
> +    # Grab de coefficients of the regression from the arduino
Spelling

2023-03-25 18:08 UTC, nicholaslegrand102 commented on prototype/gradient_descent/gradient_descent.ino
> +extern "C" {
Extern is not needed for the import

2023-03-25 18:08 UTC, nicholaslegrand102 commented on prototype/utils/arduino_serial_port.h
> +<<<<<<< HEAD
Unfinished merge

2023-03-30 18:59 UTC, zedfly commented on prototype/gradient_descent/anomaly_detection.py
> +    #detectAnomaly("data/Cubic_20%_outliers.csv", 3, 3000)
done

2023-03-31 00:21 UTC, bisson2000 approved these changes
lgtm

2023-03-31 12:38 UTC, felix642 requested changes

2023-03-31 12:38 UTC, felix642 commented on prototype/gradient_descent_anomaly_detection/README.md
> +The current prototype offers the necessary logic to perform simple anomaly detection on data points comming from a CSV file.
comming

2023-03-31 12:38 UTC, felix642 commented on prototype/gradient_descent_anomaly_detection/README.md
> +A python script will the use these coefficients to predict the next data point and check if it is close to the next data point from the CSV file.
"will the use"

2023-03-31 12:38 UTC, felix642 commented on prototype/gradient_descent_anomaly_detection/anomaly_detection.py
> +        # If the value is to far off the prediction. It is probably an anomaly
to far off

2023-03-31 12:38 UTC, felix642 commented on Makefile
> +gradient_descent: ./$(TEST_FOLDER)/test_gradient_descent.c ./src/gradient_descent.c | build_folder
Please remove this entry from the Makefile.

2023-03-31 13:45 UTC, felix642 approved these changes
LGTM!

2023-03-31 15:49 UTC, merged